spring.application.name=socialties

spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=${DRIVER_CLASS_NAME}
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${TOKEN_SECRET}
api.security.token.expires=${TOKEN_EXPIRATION_DAYS}

storage.location=${STORAGE_LOCATION}