spring.application.name=socialties

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create

api.security.token.secret=veryverysecrettoken
api.security.token.expires=7

storage.location=uploads
storage.type=LOCAL

spring.servlet.multipart.max-file-size=-1